# 全局設置
global:
  environment: production
  imageRegistry: ""

# 後端服務配置
backend:
  name: dataisec-backend
  image:
    repository: dreamerbaboo/dataisec-pod-management
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 3001
  
  # 存儲配置
  storage:
    className: "local-storage"
    size: "5Gi"
    templates:
      enabled: true
      path: "/app/deploymentTemplate"
      size: "1Gi"
    helm:
      cacheSize: "1Gi"
  
  # 安全上下文配置
  securityContext:
    container:
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: true
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN"]
    pod:
      fsGroup: 1000
      runAsUser: 1000
      runAsGroup: 1000
  
  config:
    jwt:
      secret: "your-jwt-secret"
    cors:
      allowedOrigins: ["http://localhost:5173"]
  
  env:
    NODE_ENV: production
    PORT: 3001
    OPENSEARCH_URL: "http://opensearch-cluster-master:9200"
    OPENSEARCH_HOST: "opensearch-cluster-master"
    OPENSEARCH_PORT: "9200"
    OPENSEARCH_USERNAME: "admin"
    OPENSEARCH_PASSWORD: "Cobr@8029@@123D"
    OPENSEARCH_POD_METRICS_INDEX: "metricbeat-*"
    OPENSEARCH_SYSTEM_METRICS_INDEX: "metricbeat-*"
    OPENSEARCH_LOGS_INDEX: "filebeat-*"
    OPENSEARCH_TEMPLATE_INDEX: "pod-deployment-templates"
    OPENSEARCH_DEPLOYMENT_LOG_INDEX: "pod-deployment-logs"
    OPENSEARCH_AUDIT_LOG_INDEX: "pod-deployment-audit"
    LOG_LEVEL: "info"
    LOG_FORMAT: "json"
    WS_HEARTBEAT_INTERVAL: "30000"
    DEPLOYMENT_TEMPLATE_PATH: "/app/deploymentTemplate"
    KUBECONFIG: "/app/.kube/config"
  
  # RBAC 配置
  serviceAccount:
    create: true
    annotations: {}
  
  # Docker 配置
  docker:
    socket:
      enabled: true
      path: /var/run/docker.sock
      mode: "666"
  
  # Kubernetes 配置
  kubernetes:
    config:
      enabled: true
      # 如果使用外部 kubeconfig，設置為 true
      external: false
      # 如果使用外部 kubeconfig，指定 secret 名稱
      secretName: ""
    
    # Helm 配置
    helm:
      enabled: true
      cacheDir: "/app/.helm"

# 前端服務配置
frontend:
  name: dataisec-frontend
  image:
    repository: dreamerbaboo/dataisec-pod-management
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 80
  config:
    apiUrl: "http://dataisec-backend:3001/api"

# Ingress 配置
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: dataisec.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend

# 持久化存儲配置
persistence:
  enabled: true
  storageClass: "local-storage"
  size: 10Gi
