apiVersion: v1
kind: ResourceQuota
metadata:
  name: opensearch-master-quota
  namespace: opensearch-master
spec:
  hard:
    requests.cpu: "400m"
    requests.memory: "4Gi"
    limits.cpu: "4000m"
    limits.memory: "8Gi"
    pods: "2"
    configmaps: "3"
    persistentvolumeclaims: "3"
    services: "3"
    secrets: "3"
    count/deployments.apps: "2"
    count/replicasets.apps: "3"
    count/statefulsets.apps: "3"
    count/jobs.batch: "10"
    count/cronjobs.batch: "10"