apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-master-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 4Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: opensearch-master-storageclass
  local:
    path: /data/opensearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-control-plane