apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: opensearch-master-1.0.0-storageclass
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false