apiVersion: v1
kind: ResourceQuota
metadata:
  name: opensearch-master-quota
  namespace: opensearch-master1
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: "6Gi"
    limits.cpu: "6000m"
    limits.memory: "6Gi"
    pods: "3"
    configmaps: "6"
    persistentvolumeclaims: "6"
    services: "6"
    secrets: "6"
    count/deployments.apps: "3"
    count/replicasets.apps: "6"
    count/statefulsets.apps: "6"
    count/jobs.batch: "10"
    count/cronjobs.batch: "10"