version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - k8s-certs:/var/run/secrets/kubernetes.io/serviceaccount:ro
    depends_on:
      - opensearch

  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

volumes:
  k8s-certs:
  opensearch-data:
