apiVersion: v1
kind: ResourceQuota
metadata:
  name: dataisec-console-quota
  namespace: default123
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: "256Mi"
    limits.cpu: "2000m"
    limits.memory: "4Gi"
    pods: "2"
    configmaps: "3"
    persistentvolumeclaims: "3"
    services: "3"
    secrets: "3"
    count/deployments.apps: "2"
    count/replicasets.apps: "3"
    count/statefulsets.apps: "3"
    count/jobs.batch: "10"
    count/cronjobs.batch: "10"