apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dataisec-console-storageclass
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false