apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.name }}-templates-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.storage.size | default "1Gi" }}
  storageClassName: {{ .Values.backend.storage.className | default "standard" }}
