apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
type: Opaque
data:
  jwt-secret: {{ .Values.backend.config.jwt.secret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-kubeconfig
type: Opaque
stringData:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: kubernetes
      cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://kubernetes.default.svc
    users:
    - name: serviceaccount
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: kubernetes
        user: serviceaccount
      name: serviceaccount
    current-context: serviceaccount
