apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataisec-platform
  labels:
    app: dataisec-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataisec-platform
  template:
    metadata:
      labels:
        app: dataisec-platform
    spec:
      serviceAccountName: dataisec-platform-sa
      nodeSelector:
        kubernetes.io/hostname: "192.168.170.126"
      containers:
        - name: dataisec-platform
          image: dreamerbaboo/dataisec-pod-management:1.0.0
          ports:
            - containerPort: 3001
              name: backend
              protocol: TCP
          envFrom:
            - configMapRef:
                name: dataisec-platform-config
            - secretRef:
                name: dataisec-platform-secret
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/containerd/containerd.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/containerd/containerd.sock
            type: Socket
