apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataisec-platform
  labels:
    app: dataisec-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataisec-platform
  template:
    metadata:
      labels:
        app: dataisec-platform
    spec:
      serviceAccountName: dataisec-platform-sa
      nodeSelector:
        kubernetes.io/hostname: "192.168.170.126"
      containers:
        - name: dataisec-platform
          image: dreamerbaboo/dataisec-pod-management:1.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CONTAINER_RUNTIME
              value: "nerdctl"
            - name: CONTAINER_NAMESPACE
              value: "k8s.io"
            - name: KUBECONFIG
              value: "/var/run/secrets/kubernetes.io/serviceaccount/kubeconfig"
          ports:
            - containerPort: 3001
              name: backend
              protocol: TCP
          envFrom:
            - configMapRef:
                name: dataisec-platform-config
            - secretRef:
                name: dataisec-platform-secret
          volumeMounts:
            - name: kube-api-access
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
            - name: kubeconfig
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount/kubeconfig
              subPath: kubeconfig
              readOnly: true
      volumes:
        - name: kube-api-access
          projected:
            sources:
            - serviceAccountToken:
                expirationSeconds: 3600
                path: token
            - configMap:
                name: kube-root-ca.crt
                items:
                - key: ca.crt
                  path: ca.crt
            - downwardAPI:
                items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        - name: kubeconfig
          configMap:
            name: kube-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-config
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://kubernetes.default.svc
      name: default
    contexts:
    - context:
        cluster: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
