apiVersion: v1
kind: ServiceAccount
metadata:
  name: dataisec-platform-sa
  namespace: dataisec

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataisec-platform-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "services", "configmaps", "secrets", "persistentvolumeclaims", "nodes", "persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "pods/attach", "pods/portforward"]
    verbs: ["get", "list", "create", "delete", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "nodes/status", "nodes/log"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
    resourceNames: ["privileged"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["hostpath"]
    verbs: ["get", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dataisec-platform-role-binding
subjects:
- kind: ServiceAccount
  name: dataisec-platform-sa
  namespace: dataisec
roleRef:
  kind: ClusterRole
  name: dataisec-platform-role
  apiGroup: rbac.authorization.k8s.io

---
# 添加對 kube-config ConfigMap 的訪問權限
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeconfig-reader
  namespace: dataisec
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["kube-config"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeconfig-reader-binding
  namespace: dataisec
subjects:
- kind: ServiceAccount
  name: dataisec-platform-sa
  namespace: dataisec
roleRef:
  kind: Role
  name: kubeconfig-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Namespace
metadata:
  name: dataisec
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false"
