apiVersion: v1
kind: ServiceAccount
metadata:
  name: dataisec-platform-sa
  namespace: dataisec

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataisec-platform-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "services", "configmaps", "secrets", "persistentvolumeclaims", "nodes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes/proxy", "pods/attach", "pods/exec", "pods/portforward", "pods/proxy"]
    verbs: ["create", "delete", "deletecollection", "patch", "update", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/debug"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dataisec-platform-role-binding
subjects:
- kind: ServiceAccount
  name: dataisec-platform-sa
  namespace: dataisec
roleRef:
  kind: ClusterRole
  name: dataisec-platform-role
  apiGroup: rbac.authorization.k8s.io

---
# 添加對 kube-config ConfigMap 的訪問權限
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeconfig-reader
  namespace: dataisec
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["kube-config"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeconfig-reader-binding
  namespace: dataisec
subjects:
- kind: ServiceAccount
  name: dataisec-platform-sa
  namespace: dataisec
roleRef:
  kind: Role
  name: kubeconfig-reader
  apiGroup: rbac.authorization.k8s.io
