apiVersion: v1
kind: Service
metadata:
  name: dataisec-platform-service
  namespace: dataisec
  labels:
    app: dataisec-platform
spec:
  type: NodePort
  ports:
    - name: backend
      port: 3001
      targetPort: 3001
      nodePort: 30002
  selector:
    app: dataisec-platform
