apiVersion: v1
kind: ResourceQuota
metadata:
  name: kafka-quota
  namespace: default
spec:
  hard:
    requests.cpu: "0.2m"
    requests.memory: "256Mi"
    limits.cpu: "0.4m"
    limits.memory: "512Mi"
    pods: "2"
    configmaps: "3"
    persistentvolumeclaims: "3"
    services: "3"
    secrets: "3"
    count/deployments.apps: "2"
    count/replicasets.apps: "3"
    count/statefulsets.apps: "3"
    count/jobs.batch: "10"
    count/cronjobs.batch: "10"